image:
  file: .gitpod.Dockerfile

#ports:
  # MySQL server
  #- port: 3306
  #  onOpen: ignore

tasks:
  - init: >
      mysql -u root -e "create database example_app" &&
      mysql -u root -p example_app < schema.sql
      
    #  cp .env.example .env &&
    # composer install